### PR TITLE
Query and results div variables

### PR DESCRIPTION
**Pull request by katelovescode**
Inspired by use with Drupal static html output

Now when calling the tipuesearch function, you can set variables queryParamName (default: q) and resultsDivID (default: #tipue_search_content).  This allows for flexibility in the case of Drupal output names/IDs, which are difficult to change.

### CODE REVIEW

**Comment by kateklemp** [comment]
I should have noted in description: by default, those parameters are set as they were hard-coded in prior versions, so they shouldn't affect existing users.

**Comment by Tipue** [comment]
Thanks. I'll add this in the forthcoming release.

**Comment by kateklemp** [comment]
Great, thank you!

**Comment by Tipue** [comment]
Sorry, I've just realised I missed this in version 5.0. I'll include it in the next release asap. Apologies.

**Comment by kateklemp** [comment]
No worries, thanks. :)

**Pull request closed without merging**
